name: Auto Update Data Log (Weather + Bitcoin)

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:     # allows manual run from Actions tab

permissions:
  contents: write  # allow workflow to push changes

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run data collector
        run: python data_collector.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data_log.csv
          git commit -m "Auto update data_log.csv [skip ci]" || echo "No changes to commit"
          git push
